### ISSUE TITLE
Compile resources as resource files

### ISSUE THREAD

**Issue by vallieresc** [martijnboland/apptext#27]
Is there  a way I can do that for production use ?

**Comment by martijnboland** [comment]
The [translations API endpoint](https://apptext.io/docs/api-public#get-translations) returns resx instead of json when you set the HTTP Accept header to 'text/microsoft-resx'.

An example with the online demo app:

```
curl 'https://demo.apptext.io/jsexample/translations/public/en/labels' -H 'X-Api-Key: 817ea5679a3c4b0fb5cd0e55d921ef19' -H 'Accept:text/microsoft-resx'
```

Is that something you could use?

**Comment by vallieresc** [comment]
Could be useful thanks.
