### ISSUE TITLE
How to inject resources programmatically in apptext

### ISSUE THREAD

**Issue by vallieresc** [martijnboland/apptext#32]
Hey, is there a way I can programmatically inject resources in apptext? In your API I see no insert or create methods. I know this goes against the way of a stringlocalizer but it would be the best approach for my app. I currently use GetString() and your add if not found feature to create all entries.

I would also like to know if it would be possible to add collections programmatically. I would like to create one collection per model as it would make it clearer to editors.

Maybe the only thing you need is additional API methods.

**Comment by martijnboland** [comment]
Currently, only the public API is documented, but AppText also has its regular REST API that can be used.
You could spy on the XHR requests that the admin app makes what that looks like. These endpoints cannot use the API-KEY authorization, but depend on how [authorization for AppText](https://apptext.io/docs/authorization) 
 is configured. 
In the meantime, I'll add Swagger/OpenAPI to the docker image and the demo app, so you can get a complete overview of REST API. BTW, the [hostappexample project](https://github.com/martijnboland/apptext/tree/main/src/HostAppExample) is also configured with Swagger. You can run that project and navigate to /swagger to see all available endpoints.

**Comment by martijnboland** [comment]
Swagger is added to the public demo. Here you can get a complete overview of the API: https://demo.apptext.io/swagger/index.html
