### ISSUE TITLE
API to create collection

### ISSUE THREAD

**Issue by vallieresc** [martijnboland/apptext#35]
Hi @martijnboland

I need a way to create a collection with your API. I don't see any way to do that. Is there a way or can you refactor to post a collection name?

Thanks.

**Comment by martijnboland** [comment]
There is a way to create a collection with the API: POST to /{appId}/collections with the following payload:

```
{
    "name":"mycollection",
    "contentType":{
        "id":"a5858fa0-63ec-4da1-bd78-1111f68f3ed9"
    },
    "listDisplayField":"text",
    "description":"description of my collection"
}
```

You'll need to know the ID of the content type of the collection. The list of content types is also available via the API /{appId}/contenttypes?includeglobalcontenttypes=true&name=Name_of_ContentType.

**Comment by vallieresch** [comment]
Done, it works!
