### ISSUE TITLE
Bug with require authentication role

### ISSUE THREAD

**Issue by vallieresch** [martijnboland/apptext#42]
In our app a user can have multiple roles and to support this I add multiple role claims and it works with the .net [Authorize] attribute. When adding required authentication to AppText I was getting a 500 error. I looked into it and it seems like AppText only supports 1 role claim. 

Would it be possible for you to add support for multiple role claims like the [Authorize] attribute does?

**Comment by vallieresch** [comment]
@martijnboland  Any news on this issue? Will this be supported?

**Comment by martijnboland** [comment]
Totally missed this issue. Yes, I think multiple role claims should just work, so I consider this a bug.

Unfortunately, I'm pretty swamped with work these days and I can not find any time soon to fix this. Is there a possibility that you give it a try to implement this yourself and submit a Pull Request?

**Comment by vallieresch** [comment]
Ok I'll try and get that fixed

**Comment by martijnboland** [comment]
Thanks for the PR. I just merged it and it works. However, I did try the HostAppExample after the merge and that fails because it can not (de)serialize the claims collection due to some circular reference issue with Newtonsoft.Json. Can you verify that this is also the case on your side?

**Comment by vallieresc** [comment]
I was never able to run the host app. I'm getting an error for the file provider:
AppText.AdminApp.Configuration.EmbeddedStaticFilesOptions.PostConfigure(string name, StaticFileOptions options) in EmbeddedStaticFilesOptions.cs
var filesProvider = new ManifestEmbeddedFileProvider(GetType().Assembly, "wwwroot");

**Comment by martijnboland** [comment]
Alright I'll see if I can fix it and create a new release.

**Comment by martijnboland** [comment]
Fixed in release v0.5.4
