### ISSUE TITLE
Cannot open lite db file with litedb explorer

### ISSUE THREAD

**Issue by vallieresc** [martijnboland/apptext#64]
Hi Martijn, I don't seem to be able to open the LiteDB database file with LiteDB Viewer 4. 

Opening a valid AppText LiteDb file used in app (currently not in use):

> Datafile is not a LiteDB database.

Opening the same app LiteDB log file:

> Selected file is not a valid LiteDB Database file.
> Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.

**Comment by martijnboland** [comment]
You can open AppText LiteDB databases (V5) with LiteDB Studio: https://github.com/mbdavid/LiteDB.Studio. I think the file format has changed between versions 4 and 5.

**Comment by vallieresc** [comment]
Got it! Works.
