### ISSUE TITLE
Handle text change on multiple instance

### ISSUE THREAD

**Issue by nrmohan** [martijnboland/apptext#85]
How can we clear the cache, when the app is hosted in a container orchestrator like Kubernetes where we will have multiple instance of same app running.  

Any help would be greatly appreciated.

**Comment by martijnboland** [comment]
You mean the cache in the AppText.Localization package for ASP.NET? That one currently uses IMemoryCache and I'm afraid that this doesn't work with multiple instances. 
To support multiple instances, IDistibutedCache should be used instead. Then, AppText should use any implementation of IDistributedCache that is supplied via the host application and default to MemoryDistributedCache if none is specified.
I'll gladly accept a Pull Request for that ;-)
